# -*- coding: utf-8 -*-
"""AlphaCFO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ry67mnXbLUJqRBeqeGpaNP29ISjddygs
"""

# ===== FINVEDA AI v1.0 - Multi-Agent CFO Dashboard =====
# Built by: [Your Name] | Tech: Python + Azure GPT-4o-mini
!pip install -q yfinance==0.2.40 plotly python-dotenv requests

import os, yfinance as yf, plotly.graph_objects as go, pandas as pd, numpy as np, requests, getpass
from datetime import datetime
from IPython.display import display, Markdown

print("=== FINVEDA AI SETUP ===")
print("Enter keys once. They are NOT saved to GitHub.")
AZURE_OPENAI_API_KEY = getpass.getpass("AZURE_OPENAI_API_KEY: ")
AZURE_OPENAI_ENDPOINT = input("AZURE_OPENAI_ENDPOINT: ").strip()
AZURE_OPENAI_DEPLOYMENT = input("AZURE_OPENAI_DEPLOYMENT: ").strip()
TICKER = input("Enter Stock Ticker e.g TSLA, AAPL, NVDA: ").strip().upper()

def azure_chat(prompt, system_role):
    """Live Azure call. Fails gracefully to Demo Mode."""
    if "xxxx" in AZURE_OPENAI_API_KEY:
        return "**DEMO MODE ACTIVE**\n1. Earnings Report Next Week\n2. Risk: Interest Rate Hikes\n3. Opportunity: AI Product Launch\n\n*Add real Azure key for live AI*"

    url = f"{AZURE_OPENAI_ENDPOINT}/openai/deployments/{AZURE_OPENAI_DEPLOYMENT}/chat/completions?api-version=2024-02-15-preview"
    headers = {"api-key": AZURE_OPENAI_API_KEY, "Content-Type": "application/json"}
    data = {"messages": [{"role": "system", "content": system_role}, {"role": "user", "content": prompt}], "max_tokens": 250}
    try:
        r = requests.post(url, headers=headers, json=data, timeout=30)
        r.raise_for_status()
        return r.json()['choices'][0]['message']['content']
    except Exception as e:
        return f"**DEMO MODE**\nAzure Error: {str(e)[:80]}...\n*Check endpoint/firewall*"

def get_live_data(ticker):
    try:
        hist = yf.Ticker(ticker).history(period="3mo", auto_adjust=True)
        if hist.empty: raise Exception()
    except:
        dates = pd.date_range(end=datetime.now(), periods=60)
        price = 200 + np.cumsum(np.random.randn(60)*2)
        hist = pd.DataFrame({'Open':price,'High':price+3,'Low':price-3,'Close':price}, index=dates)
    return hist

def create_chart(hist, ticker):
    fig = go.Figure(go.Candlestick(x=hist.index, open=hist['Open'], high=hist['High'], low=hist['Low'], close=hist['Close']))
    fig.update_layout(title=f'📈 {ticker} - 3M Chart', template="plotly_dark", height=400, xaxis_rangeslider_visible=False)
    fig.show()

# === RUN DASHBOARD ===
hist = get_live_data(TICKER)
last_price, ma20 = hist['Close'].iloc[-1], hist['Close'].rolling(20).mean().iloc[-1]
create_chart(hist, TICKER)

display(Markdown(f"### 🚀 FinVeda AI: Multi-Agent CFO | {TICKER}"))
display(Markdown(f"**Powered by Azure GPT-4o-mini** | Price: `${last_price:.2f}` | {datetime.now().strftime('%Y-%m-%d %H:%M')}"))
display(Markdown("---"))
display(Markdown("### 📰 NEWS AGENT")); display(Markdown(azure_chat(f"Top 3 news/risks/opps for {TICKER}", "You are a Bloomberg Analyst")))
display(Markdown("### 📊 QUANT AGENT")); display(Markdown(azure_chat(f"Price {last_price:.2f}, MA20 {ma20:.2f}. BUY/SELL/HOLD + 1 reason for {TICKER}", "You are a Wall Street Quant")))
display(Markdown("### 💼 PORTFOLIO AGENT")); display(Markdown(azure_chat(f"1M outlook, Risk/10, Allocation% for {TICKER} at {last_price:.2f}", "You are an AI CFO")))